
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./paewindowassets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("446x596")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 596,
    width = 446,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    446.0,
    596.0,
    fill="#CF92C9",
    outline="")

canvas.create_text(
    38.0,
    13.0,
    anchor="nw",
    text="Medical Prescription and Analysis",
    fill="#AC009A",
    font=("Quicksand Regular", 24 * -1)
)

canvas.create_text(
    38.0,
    53.0,
    anchor="nw",
    text="by",
    fill="#000000",
    font=("Quicksand Regular", 16 * -1)
)

canvas.create_text(
    67.0,
    53.0,
    anchor="nw",
    text="Dr example Name",
    fill="#000000",
    font=("Quicksand Regular", 16 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    223.0,
    330.0,
    image=image_image_1
)

canvas.create_text(
    25.0,
    96.0,
    anchor="nw",
    text="Description",
    fill="#000000",
    font=("Quicksand Regular", 16 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    223.0,
    431.0,
    image=image_image_2
)

canvas.create_text(
    38.0,
    365.0,
    anchor="nw",
    text="Medicine Prescribed",
    fill="#CF92C9",
    font=("Quicksand Regular", 20 * -1)
)

canvas.create_text(
    38.0,
    411.0,
    anchor="nw",
    text="Medicine",
    fill="#000000",
    font=("Quicksand Regular", 20 * -1)
)

canvas.create_text(
    38.0,
    466.0,
    anchor="nw",
    text="Duration:",
    fill="#CF92C9",
    font=("Quicksand Regular", 20 * -1)
)

canvas.create_text(
    134.0,
    466.0,
    anchor="nw",
    text="Time",
    fill="#000000",
    font=("Quicksand Regular", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
